### ISSUE TITLE
update to latest minecraft version

### ISSUE THREAD

**Issue by thewanderingtraderm** [Ultreon/gdx-minecraft#1]

**Comment by QboiDev** [comment]
:pain:

**Comment by thewanderingtraderm** [comment]
atleast make a compiled version because i want to try it out and compiling it gives me errors

**Comment by QboiDev** [comment]
Well, trying it out is kinda useless as it's a library mod.
Unless you are going to make something with it :shrug:

**Comment by QboiDev** [comment]
Compiling should work now in commit https://github.com/Ultreon/mcgdx/commit/8c4362b7d5f57bf9fc4621636472cb27b25dafcf

**Comment by thewanderingtraderm** [comment]
now when I run it the game crashes.
This is the crash report:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-05-04 14:52:53
Description: Unexpected error

java.lang.IllegalArgumentException: Error compiling shader: Vertex shader
ERROR: 0:1: '' : syntax error: #version directive must occur in a shader before anything else

Fragment shader:
ERROR: 0:5: '' : syntax error: #version directive must occur in a shader before anything else
ERROR: 0:5: '' : illegal order of preprocessor directives 


	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:164)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:127)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:81)
	at io.github.ultreon.gdxminecraft.GdxMinecraft.initialize(GdxMinecraft.java:73)
	at io.github.ultreon.gdxminecraft.GdxMinecraft.create(GdxMinecraft.java:86)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.invokeUpdate(Lwjgl3Window.java)
	at io.github.ultreon.gdxminecraft.impl.MinecraftApplication.update(MinecraftApplication.java:139)
	at net.minecraft.client.Minecraft.handler$zlh000$gdx_minecraft$createTickProfiler(Minecraft.java:6606)
	at net.minecraft.client.Minecraft.run(Minecraft.java:850)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:164)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:127)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:81)
	at io.github.ultreon.gdxminecraft.GdxMinecraft.initialize(GdxMinecraft.java:73)
	at io.github.ultreon.gdxminecraft.GdxMinecraft.create(GdxMinecraft.java:86)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.invokeUpdate(Lwjgl3Window.java)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.fillCrashReport(ResourceLoadStateTracker.java:49)
	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2488)
	at net.minecraft.client.Minecraft.run(Minecraft.java:880)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 20.0.2.1, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 338324352 bytes (322 MiB) / 1021313024 bytes (974 MiB) up to 4217372672 bytes (4022 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Ti Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x24a0
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5123
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x46a6
	Graphics card #1 versionInfo: DriverVersion=31.0.101.3413
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32471.64
	Virtual memory used (MB): 12254.49
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 23.38
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric-api: Fabric API 0.90.7+1.20.2
		fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
		fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
		fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
		fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
		fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
		fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
		fabric-containers-v0: Fabric Containers (v0) 0.1.75+df3654b3a0
		fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.5+b1792f7da0
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.16+b1792f7da0
		fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
		fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
		fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
		fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
		fabric-networking-api-v1: Fabric Networking API (v1) 3.0.11+bff13c85a0
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
		fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
		fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.8+52b3ebe5a0
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.6+b1792f7da0
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
		fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.10+e3d2bf3fa0
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.41+b1792f7da0
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
		fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.10+bb1ee60ea0
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.14.24
		gdx_minecraft: LibGDX for Minecraft 0.1.0+devtest.2
		generated_4c24433: Generated Mod (Please Ignore) 1.0.0
		java: OpenJDK 64-Bit Server VM 20
		minecraft: Minecraft 1.20.2
		modmenu: Mod Menu 8.0.0
	JVM uptime in seconds: 17.864
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 31.0.101.3413, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=0, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_COMPILE error has been generated. GLSL compile failed for shader 28, "": ERROR: 0:1: '' : syntax error: #version directive must occur in a shader before anything else

' x 1
id=0, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_COMPILE error has been generated. GLSL compile failed for shader 29, "": ERROR: 0:5: '' : syntax error: #version directive must occur in a shader before anything else
ERROR: 0:5: '' : illegal order of preprocessor directives 

' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_US
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700H

**Comment by QboiDev** [comment]
I think that is unsupported GPU/hardware...
It uses OpenGL 3.2.0...

At least an issue with compiling the shader within libGDX.

**Comment by QboiDev** [comment]
I think at least OpenGL 4.3 is required. But I can be wrong.

**Comment by thewanderingtraderm** [comment]
it works but there are some issues now such as the screen flickering and the brightness being a bit low, also when vsync is on the screen flickers a lot and shows black lines
